### ISSUE TITLE
freetype 2.6.3 Build Failed On VS2012/VS2015

### ISSUE THREAD

**Issue by lpyvvvvvv** [krkrz/freetype#1]
error C2099 initializer is not a constant 
freetype-2.6.3\src\autofit\afstyles.h 100 
error C2065 “AF_SCRIPT_CYRL”: undeclared identifier 
freetype-2.6.3\src\autofit\afstyles.h 100 
it happend on freetype-2.6.3. but freetype-2.6.2 success build.

**Comment by jin1016** [comment]
吉里吉里Z本体のビルドを行いましたが、FreeTypeでは特に問題は発生しませんでした。
